version: '3.8'
services:
  db:
    container_name: 'postgres'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=jakwywioze
      - POSTGRES_PASSWORD=jakwywioze
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    container_name: 'spring-boot-backend'
    build: .
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=jakwywioze
      - SPRING_DATASOURCE_PASSWORD=jakwywioze
    depends_on:
      - db
volumes:
  db:
    driver: local
